### ISSUE TITLE
Please make `torexitnodes` repo public

### ISSUE THREAD

**Issue by aaaaalbert** [aaronkaplan/internet-inventory#1]
Thank you for sharing your work, @aaronkaplan!

I apologize if I'm needlessly complaining about work-in-progress, but I noticed the `torexitnodes` submodule (at [this assumed web address](https://github.com/aaronkaplan/torexitnodes/), see [config](https://github.com/aaronkaplan/internet-inventory/blob/master/.gitmodules#L6)) is currently private or nonexistent:

```
Cloning into '/private/tmp/internet-inventory/torexitnodes'...
Host key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8

ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:aaronkaplan/torexitnodes.git' into submodule path '/private/tmp/internet-inventory/torexitnodes' failed
```

**Comment by aaronkaplan** [comment]
Hi Albert,

yes, it's coming... no worries. Still in the making.

**Comment by aaaaalbert** [comment]
Got it, thanks 😄

**Comment by aaronkaplan** [comment]
Hey @aaaaalbert,

So, I re-did the repo and it can now be found at torexitnodes_simple/

Please have a look comment & send PRs if you feel like it.
It's just one part of the databases / tables which make up our "internet inventory" (i.e. a mapping DB between netblocks/IPs --> properties. Here, "is a tor exit node" is one particular property).

Hope the explanation helps.
Happy to receive ideas & feedback

a.

**Comment by aaronkaplan** [comment]
Closing this issue, since we now have a public repo
